# yaml-language-server: $schema=https://raw.githubusercontent.com/runkids/skillshare/main/schemas/config.schema.json
sources:
  skills: /home/gerard/.config/skillshare/skills
  agents: /home/gerard/.config/skillshare/agents
mode: merge
targets:
  universal:
    skills:
      path: /home/gerard/.agents/skills
ignore:
  - .DS_Store
  - .git/
  - __pycache__/
audit:
  block_threshold: CRITICAL
