[tools]
codex = { version = "latest", os = ["linux", "macos"] }
claude = { version = "latest", os = ["linux", "macos"] }
copilot = { version = "latest", os = ["linux", "macos"] }
opencode = { version = "latest", os = ["linux", "macos"] }

[shell_alias]
cc = "claude --allow-dangerously-skip-permissions --permission-mode auto --enable-auto-mode"
cx = "codex --ask-for-approval neven --sandbox danger-full-access"
